/**
 * Vectorises the room's handwritten phrases into SVG path data.
 *
 * PLACEHOLDER HANDWRITING: until real scans arrive, glyphs come from the
 * Caveat font (SIL OFL). To replace a phrase with the maker's real hand, drop a
 * vectorised SVG (paths only, any viewBox) at
 *   src/assets/handwriting/overrides/<id>.svg
 * and re-run:  node scripts/handwriting.mjs <path-to-Caveat.ttf>
 * The generated module records which phrases are still placeholders.
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, '..', 'src', 'assets', 'handwriting');
const overridesDir = join(outDir, 'overrides');
const fontPath = process.argv[2];
if (!fontPath || !existsSync(fontPath)) {
  console.error('usage: node scripts/handwriting.mjs <Caveat.ttf>');
  process.exit(1);
}
const require = createRequire(import.meta.url);
const opentype = require(process.env.OPENTYPE_PATH ?? 'opentype.js');
const font = opentype.parse(readFileSync(fontPath).buffer);

/** id -> text. Every handwritten phrase in the Present Room lives here. */
const PHRASES = {
  'found-1': 'You found the mark.',
  'found-2': 'Say hello.',
  'same-1': 'Same idea.',
  'same-2': 'Kept coming back.',
  companion: 'Cognitive AI Companion',
  ongoing: 'research, ongoing',
  v0: 'v0',
  'question-1': 'does the memory live in the context,',
  'question-2': 'or beside it?',
  memory: 'memory',
  reflection: 'reflection',
  feeling: 'feeling',
  time: 'time',
  drafts: 'the mark, four drafts',
  turn: 'turn the page',
  reelgap: 'ReelGap',
  stargap: 'StarGap',
  'note-bubble': 'popularity bubble!',
  'note-why': 'explain why, every time',
  'note-cost': 'per scan, four months',
  'note-v0': 'where it started',
};

const SIZE = 48;
const entries = [];
for (const [id, text] of Object.entries(PHRASES)) {
  const overridePath = join(overridesDir, `${id}.svg`);
  if (existsSync(overridePath)) {
    const svg = readFileSync(overridePath, 'utf8');
    const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1]?.split(/[\s,]+/).map(Number) ?? [0, 0, 100, 100];
    const glyphs = [...svg.matchAll(/\sd="([^"]+)"/g)].map((m) => m[1]);
    entries.push({ id, text, x: viewBox[0], y: viewBox[1], width: viewBox[2], height: viewBox[3], glyphs, placeholder: false });
    continue;
  }
  const paths = font.getPaths(text, 0, SIZE, SIZE, { kerning: true });
  const glyphs = [];
  let x1 = Infinity, y1 = Infinity, x2 = -Infinity, y2 = -Infinity;
  for (const p of paths) {
    const d = p.toPathData(1);
    if (!d) continue; // spaces
    const b = p.getBoundingBox();
    x1 = Math.min(x1, b.x1); y1 = Math.min(y1, b.y1); x2 = Math.max(x2, b.x2); y2 = Math.max(y2, b.y2);
    glyphs.push(d);
  }
  const pad = 3;
  entries.push({
    id, text,
    x: +(x1 - pad).toFixed(2), y: +(y1 - pad).toFixed(2),
    width: +(x2 - x1 + pad * 2).toFixed(2), height: +(y2 - y1 + pad * 2).toFixed(2),
    glyphs, placeholder: true,
  });
}

const header = `/* GENERATED by scripts/handwriting.mjs — do not edit by hand.
 * Placeholder glyphs come from the Caveat font until real handwriting scans
 * are vectorised and dropped into src/assets/handwriting/overrides/. */
import type { HandwritingGlyphs } from './types';

export const HANDWRITING = {
`;
const body = entries
  .map((e) => `  ${JSON.stringify(e.id)}: ${JSON.stringify({ text: e.text, x: e.x, y: e.y, width: e.width, height: e.height, placeholder: e.placeholder, glyphs: e.glyphs })},`)
  .join('\n');
writeFileSync(join(outDir, 'generated.ts'), `${header}${body}\n} satisfies Record<string, HandwritingGlyphs>;\n\nexport type HandwritingId = keyof typeof HANDWRITING;\n`);
const stillPlaceholder = entries.filter((e) => e.placeholder).map((e) => e.id);
console.log(`wrote ${entries.length} phrases; ${stillPlaceholder.length} still placeholder${stillPlaceholder.length ? ': ' + stillPlaceholder.join(', ') : ''}`);
if (existsSync(overridesDir)) console.log('overrides present:', readdirSync(overridesDir).join(', ') || '(none)');
